# Client (Frontend) - Cloud Build Configuration
# Trigger path: client/**

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/chattoner-client:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/chattoner-client:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'client'
    id: 'build-client-image'

  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/chattoner-client:latest'
    id: 'push-client-latest'

  # Push commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/chattoner-client:$COMMIT_SHA'
    id: 'push-client-sha'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'client'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chattoner-client:latest'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '60'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    id: 'deploy-client-cloudrun'

# Images to be stored in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/chattoner-client:latest'
  - 'gcr.io/$PROJECT_ID/chattoner-client:$COMMIT_SHA'

# Build timeout
timeout: '1200s'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
