version: "3.9"

services:
  backend:
    build: ./python_backend
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/chattoner-db
      - port: 8080
    ports:
      - "8080:8080"
    command: [ "uvicorn", "run_fastapi:app", "--host", "0.0.0.0", "--port", "8080" ]
    depends_on:
      - db:
        condition: service_healthy
    restart: unless-stopped

  gateway:
    build:
      context: ./nestjs-gateway
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - BACKEND_API_URL=http://backend:8080
      - port=3000
    ports:
      - "3000:3000"
    depends_on:
      - backend:
        condition: service_started
    restart: unless-stopped

  db:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      POSTGRES_DB: chattoner-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\"" ]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata: {}
