# Database Migration Cloud Build Configuration
# Trigger: Manual or on-demand for database schema updates

steps:
  # Run PostgreSQL migrations
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing PostgreSQL client..."
        apt-get update -qq && apt-get install -y -qq postgresql-client > /dev/null 2>&1

        echo "Starting database migrations..."

        # Run each migration file in order
        for migration in python_backend/db/migrations/*.sql; do
          if [ -f "$$migration" ]; then
            echo "Applying migration: $$(basename $$migration)"
            psql "$$DATABASE_URL" -f "$$migration" -v ON_ERROR_STOP=1 || {
              echo "Migration $$(basename $$migration) failed or already applied"
            }
          fi
        done

        echo "Database migrations completed!"
    secretEnv: ['DATABASE_URL']
    id: 'run-migrations'

# Secret management - DATABASE_URL from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'

# Build options
options:
  machineType: 'E2_MEDIUM'
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'
