# NestJS Gateway - Cloud Build Configuration
# Trigger path: nestjs-gateway/**

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/chattoner-gateway:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/chattoner-gateway:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'nestjs-gateway'
    id: 'build-gateway-image'

  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/chattoner-gateway:latest'
    id: 'push-gateway-latest'

  # Push commit SHA tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/chattoner-gateway:$COMMIT_SHA'
    id: 'push-gateway-sha'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'chattoner-gateway'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chattoner-gateway:latest'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '60'
      - '--concurrency'
      - '100'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=3000,BACKEND_API_URL=http://52.79.96.121:8080'
    id: 'deploy-gateway-cloudrun'

# Images to be stored in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/chattoner-gateway:latest'
  - 'gcr.io/$PROJECT_ID/chattoner-gateway:$COMMIT_SHA'

# Build timeout
timeout: '1200s'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
